import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import styles from './page.module.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.layout_container}>
          <Sidebar />
          
          {children}
        </div>
      </body>
    </html>
  )
}
